#' Plot result of ipa
#'
#' This function allows you to plot multiple independent ipa analyses.
#' @param x A dataframe output generated by the ipa function
#' @param cutoff The number of pathways to plot. Defaults to 10
#' @keywords plot ipa
#' @export
#' @return Barplot of ipa result
#' @examples
#' data(kData)
#' data(rData)
#' ipaResult<-ipa(geneResult=kData, metaboliteResult=rData, combine=TRUE, 
#'      geneCutoff=0.1, metaboliteCutoff=0.219)
#' plotIPA(ipaResult)


plotIPA = function(x, cutoff=10){
  
  toPlot <- x[order(x[,3]),][1:cutoff,]
  Annotation = factor(row.names(toPlot), levels = unique(row.names(toPlot)))
  if(length(grep("Fold_Change", colnames(toPlot)))>0){
    mid=0
    p1 = ggplot2::qplot(Annotation, -log(toPlot[,2], base=2), geom= "bar", stat="identity", binwidth= 0.00001, fill = toPlot[,grep("Fold_Change", colnames(toPlot))[1]])
    p2 = p1 + ggplot2::scale_fill_gradient2(midpoint = mid, "Fold Change", limits = c(min(x[,grep("Fold_Change", colnames(toPlot))[1]]),max(x[,grep("Fold_Change", colnames(toPlot))[1]])), low = "blue",mid = "black", high = "red", space = "Lab" )
    p3 = p2 + ggplot2::ylab("Negative Log FDR")+ggplot2::xlab("")+ggplot2::coord_flip() + ggplot2::theme( panel.background = ggplot2::element_blank(), panel.grid = ggplot2::element_blank(), axis.line = ggplot2::element_line(colour = "black", size = 1), axis.text = ggplot2::element_text(face = "bold", colour = "black"),  axis.ticks = ggplot2::element_line(colour = "black"), axis.title = ggplot2::element_text(face="bold", colour = "black"))
    return(p3)
  }
  else{
    p1 = ggplot2::qplot(Annotation, -log(toPlot[,2], base=2), geom= "bar", stat="identity", binwidth= 0.00001)
    p2 = p1 + ggplot2::ylab("Negative Log FDR")+ggplot2::xlab("")+ggplot2::coord_flip() + ggplot2::theme( panel.background = ggplot2::element_blank(), panel.grid = ggplot2::element_blank(), axis.line = ggplot2::element_line(colour = "black", size = 1), axis.text = ggplot2::element_text(face = "bold", colour = "black"),  axis.ticks = ggplot2::element_line(colour = "black"), axis.title = ggplot2::element_text(face="bold", colour = "black"))
    return(p2)
  }
}